### PR TITLE
Entry Recommited, Allong with Build for Puzzle 1 to 4.

### PR DESCRIPTION
**Pull request by Sterritt42Strat**
Added a large number of maya models, Starting space, Puzzle 1-4 and a Large terrain all in scene Entry. Folders in Prefab are now organized by when the model was created. Also working with the Unity Environment package for tree and textures.

Trouble with running FMOD, Player/Camera Controls, Alpaca AI update and in need of original textures. 

Signed-off-by: James Sterritt <James Sterritt>

### CODE REVIEW

**Comment by mightypants** [comment]
It's difficult to navigate through all the contents of the Unity project--we need to establish logical naming conventions and folder structure.  For example, there are folders Gen 1, Gen 2, Gen 3 in Prefabs.  There's really no need to keep multiple version of these contents within Unity--that's what Git is for.  Also, there are multiple Materials folders, and textures buried a few levels deep. 

Can you please restructure in a way that will make sense for our final game and make it easy to find what is needed?

**Comment by mightypants** [comment]
Additionally, things that can/should be removed:
all the tb.JS.11.6 stuff
Standard Assets/CrossPlatformInput
Standard Assets/Utility
any previously created temp assets that are no longer needed

**Comment by mightypants** [comment]
Just wanted to add: I'm happy to do this cleanup, but I didn't want to go in and mess with stuff you've done without talking about it first.  I do want to get to combining work as soon as possible, though, so I may go head with these changes later this afternoon if I haven't heard back from you beforehand.

**Comment by Sterritt42Strat** [comment]
Thanks for cleaning up the files Jonnie, I also realized some of my errors with file changing within Git. My second commit has you far better file structure, a pile of textures, more into prefab, and a couple of key dimenson changes.

Use this for today's merge, once somebody else tests it.

**Pull request closed without merging**
